# Generated by Django 2.1.1 on 2018-09-23 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date record created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')),
                ('number', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('th', 'Thingy'), ('dl', 'Dealy'), ('fl', 'Flubber')], help_text='The type of widget this is.', max_length=2, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='user who created record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Widget_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='user who most recently modified record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Widget_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date record created.')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='date of most recent record modification.')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Planned'), (2, 'Locked'), (3, 'Running'), (4, 'Complete'), (5, 'Error')], db_index=True, default=(1, 'Planned'), verbose_name='Run Status')),
                ('created_by', models.ForeignKey(blank=True, help_text='user who created record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WidgetRun_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='user who most recently modified record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WidgetRun_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
