# Generated by Django 2.1.1 on 2018-09-25 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='number',
        ),
        migrations.AddField(
            model_name='widget',
            name='description',
            field=models.CharField(blank=True, help_text='A description of this widget', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='widget_number',
            field=models.CharField(default=1, help_text='The unqiue identifier for this particular widget.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgetrun',
            name='widget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.Widget'),
            preserve_default=False,
        ),
    ]
